POST https://enstooffer.azurewebsites.net/Offer HTTP/1.1
content-type: application/json

{
    "structure_type": "support",
    "structure_id": "А11",
    "parts": [
      {"Id_x": "ЗП6", "StructureId":  "К25-к"},
      {"Id_x": "П-3и", "StructureId":  "А10-1+КМ-1 _(50мм²)"},
      {"Id_x": "СВ95-3", "StructureId":  "УП23-1отт"},
      {"Id_x": "У4", "StructureId":  "А10-2+КРМ-2 _(50 мм²)"},
      {"Id_x": "COT36.2", "StructureId":  "УП12с_в2"},
      {"Id_x": "COT37.2", "StructureId":  "ОАБ10/04-8_(70-95 мм²)"},
      {"Id_x": "PER15", "StructureId":  "Установка ШУОС на КТП"},
      {"Id_x": "SH702R", "StructureId":  "А12с"},
      {"Id_x": "SL37.2", "StructureId":  "КтБ10-21"},
      {"Id_x": "SLIP22.1", "StructureId":  "П10/04-8"},
      {"Id_x": "SLIP22.127", "StructureId":  "П10/04-8"},
      {"Id_x": "SO250.01", "StructureId":  "ККМкв вар.4"},
      {"Id_x": "SOT29.10R", "StructureId":  "П10/04-8"}
    ]
}