POST http://127.0.0.1:8000/api/ HTTP/1.1
#POST http://dev.lep10.ru:8000/api/ HTTP/1.1
content-type: application/json

{
    "structure_type": "support10",
    "structure_id": "А10-20МИ-4Ш",
    "parts": [
        "ЗП1, 1.10-20.МИ.15-93",
        "ЛК 70/10-И-4 ГС",
        "ОАЗ-1",
        "П103И, 1.10-20.МИ.15-94",
        "ПС-2-1А",
        "СВ110-5",
        "СК-7-1А",
        "ТМ 75И, 1.10-20.МИ.15-75",
        "У52И, 1.10-20.МИ.15-83"
    ]
}