POST http://127.0.0.1:8000/api/ HTTP/1.1
#POST http://dev.lep10.ru:8000/api/ HTTP/1.1
content-type: application/json

{
    "structure_type": "support10",
    "structure_id": "П20-3Н",
    "parts": [
        "К9",
        "РМК-20-IV-УХЛ1",
        "СВ 70",
        "СВ110-5",
        "ТМ63, 27.0002-28",
        "Х51, 27.0002-42",
        "CD 35",
        "IF 27"
    ]
}